### ISSUE TITLE
How to get older versions of monitor version 8?

### ISSUE THREAD

**Issue by erikdsjostrom** [lgrn/op5-vagrant#4]
I want to provision a machine using monitor version 8.2.1 but just updating one of the links in the provision script did not work. Is this a known issue?

**Comment by lgrn** [comment]
The latest version has a Vagrantfile that has a line like this:

```
centos7.vm.provision "shell", path: "provision.sh", :args => "-r -v -m 8.2.1"
```

Replace the value in the `-m` flag and it will be fetched, assuming it's a new enough version, some older ones fail. Note that this file is kept across vagrant runs, so if you previously selected a newer version, you need to delete that file from the Vagrant directory for this flag to matter.

Documentation for provision.sh is available by running the script with no flags.
